### ISSUE TITLE
актуальный API NER

### ISSUE THREAD

**Issue by RadionBik** [natasha/slovnet#1]
Добрый день!

Судя по всему, на данный момент имеется расхождение минимального примера из readme  и актуальным API библиотеки, т.к. у функции NER нет аттрибута navec, во-вторых объект NERinfer возвращает генератор, который при распаковке ничего не возвращает. Подскажите, что я упускаю?

Также, было бы здорово хотя бы в тезисах увидеть документацию по обучению под кастомную задачу: формат датасета и минимальный код для этого.

P.S. планируется ли заморозка API? неделю назад интерфейс был другим, а по тегу релиза README нет

**Comment by kuk** [comment]
> Судя по всему, на данный момент имеется расхождение минимального примера из readme и актуальным API библиотеки, т.к. у функции NER нет аттрибута navec, во-вторых объект NERinfer возвращает генератор, который при распаковке ничего не возвращает. Подскажите, что я упускаю?

API поменялся, примеры в README https://github.com/natasha/slovnet
Обратите внимание, что изменились файлы с весами. Также кроме весов нужно скачать файл navec

> Также, было бы здорово хотя бы в тезисах увидеть документацию по обучению под кастомную задачу: формат датасета и минимальный код для этого.

Документации по обучению нет, есть код скриптов https://github.com/natasha/slovnet/blob/master/scripts/02_bert_ner/main.ipynb https://github.com/natasha/slovnet/blob/master/scripts/05_ner/main.ipynb

> P.S. планируется ли заморозка API? неделю назад интерфейс был другим, а по тегу релиза README нет

Пока не планируется
